# Generated by Django 5.2.4 on 2025-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_current_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_debt',
            field=models.FloatField(default=0),
        ),
    ]
