# Generated by Django 5.2.4 on 2025-08-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_remove_customer_current_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('tenure', models.IntegerField(help_text='Tenure in months')),
                ('interest_rate', models.FloatField(help_text='Annual interest rate (e.g., 13.5)')),
                ('monthly_installment', models.FloatField()),
                ('emis_paid_on_time', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer')),
            ],
        ),
    ]
